#!/bin/sh

cd /etc/firewall.d
python rules.py


/sbin/iptables-restore < /etc/firewall.d/rules
mkdir -p /etc/firewall.d/old.rules
cp /etc/firewall.d/rules "/etc/firewall.d/old.rules/rules-$(date '+%F %T')"
