#! /bin/sh

# Abort if any command returns an error value
set -e

case "$1" in
  purge)
    # This package has previously been removed and is now having
    # its configuration purged from the system.
    :

    # remove the configuration file itself
    rm -rf /etc/berlin

    ;;
esac

#DEBHELPER#
